{% set version = "1.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-glm2
  version: {{ version|replace("-", "_") }}

source:
  fn: glm2_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/glm2_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/glm2/glm2_{{ version }}.tar.gz

  sha256: 5a5190ce0fb12944d2a3b739020b264933f72ba5341ea11624c4c0f8cfc77225

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('glm2')"  # [not win]
    - "\"%R%\" -e \"library('glm2')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=glm2
  license: GPL (>= 2)
  summary: Fits generalized linear models using the same model specification as glm in the stats
    package, but with a modified default fitting method that provides greater stability
    for models that may fail to converge using glm.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - Johanneskoester
    - Bgruening
    - Daler
    - Jdblischak
