travis:
  secure:
    BINSTAR_TOKEN: g1TdEQOhJGS/+GedvDbEl/oRLILU1eRMkq7KM4nn9LUAZSa0y8GtV/IMWdo4WnFJVspdVsPca30BBNTFI80L2onUxV67Eox6SaO6QXr3lGcyjaBFTWqZV8lRE3vQqh0plYenNgvOe5fxNpqjPqtioh60Bzb66B6LdI8hPfKsyuJQEOc1okvW/suhlbyk1Uld6lfqP2svJlNFvbmTTIb5MX3HJJ8OVtIU3/jbQUua8efCenyP3CfLBmbfMKu1OOerIgDWAk0VVK3a3mamvs5R88FAihNqdZ1YSYvE99dEiro2jQZ2dnINwuPJB81fpwMaxaPxxmwStVuIliSuKrf8C2Zg1afzA9YYW2sA2wl/Qqwj4RXadAKqJmFc3H2tcJ4eeRJ9z6ZoRUerVKsSI/r+c74xYH/w/j64gL3xpexPEHHE9FGBtuhPim2zXjr2miUiL2fLjL/ceQOJgZIbjv1Ede1iQid3JNyb0BBpjeLF37a4Oqdb0/FAmXgqPjixNl8jtQwOIBSpfatewkxaLIRvwgimr9kfEqp2/SbI5wFclKcMgDWzyWqW3p6sDZClel9sRI16lcIvpeA4Y+Q8bdEfr6fV776Nlgu/6wBmjv4EvGxLjVpGTFHxfFpVWXrUqXd3KzX5p50mHPy1qf1AvTxJ6FWIWb/R8TRAtYlVbSvcLEY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
