appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: KmCEGSCRupjpo2DSTDIjFQuoLI0JSLiN2mXhv/d42F+tbAdxHISmVStPMJzT4Qz+fVjviwIr6EnCSIwxrncdaon4gTr6DhWTiV0LpzV+xTEm8bw0AL8aEZg5QYBM4n2hRyEc+fdtz/vwEyTpjv5Tqp1fcgn9FbLawDoRwK+E4f6+/96pj02KyLGMOiKOCQOOfek4ZDs+Wk+MzTNoTWmvJYb5RilbFrSicWI/rTAJ5DWU+hy2u/bek4eF8JJFcmyp2rwmGJZjcTmVVn9JK14jzRxccBxIjIqgt+x5Rb6t27XkN8lQPA7hYfvlkY77HrzL27bsqqxxrSXz9KAPPjCy1k0QlS4pFABCHuHn+6x2xIcNdVPD+nT14xPzT0/KIHXir7WojZV6GvRf05XvsBiWaKVB/ZbSevcEuaXpNaUKwhMwWQaTtWDNO51ERBg6bxxHOLly8lc++zAvIauTgP0Vi6nMtasmmW3YtRHMVWb4c6Rn4Ep8oT3xrctgOMM89ZDfQ8JDPsy4k+UT7wJekQXvCZcF2baKSByC7okSR3RhK8VAvreHgnDDs0K5nZTkRrIT3I4LKiHIbYDcHwi19cHt9FKMd4mAhsMoxwXsvmvWuLD8ZkXEkWpTUOI1Iz7DQ4hTXl2bgK4Sa2unXnJakBYcR0MMZBNZkUvY8JFnb9F9pSg=}
