travis:
  secure:
    BINSTAR_TOKEN: FkfOsKbFjqQmidEagnfenQRghG9s3Zm6QNboAeM/OxpuniDLxuiBGcGXcXZ/i1xGQKFpWBP8h2dYXRd0ojbUbHb99Z0hdGLbCVYgS/fJy4ahgb1Ye2NuazEN2L4M6Xeu4OB2aix+YDRLgolyLCdkE8a/CIsaHbFOJ9CW1poYnB36aFZ+ZbRySAKcYZN3Ghc40D4mudS9jyfrRjPbXYrhMT34r8XoTXqk6BzRNoe/uFzw3UBd4xdqUZWsHqXpDvQA+MDEXdae6bdYPNdd+a5q/IoBYFxG7gEgB5/EZQ1f0xpIf3rmBmbsAHAcm/rhbgQqaZwrg1GyTxOWjENcXQV1w8qrFPxyqC/ooURwupQk1EH3zpTID7C/fQofi51hKOumkFBgF8quTmIzplpPet6LSGeuAkmzv/Pz2hTRzD018e2GHU7tG+ziF0Gs/Nki5ZKHfD1vuYZJTNKqVAVwUTmH5nAGnz7M4nTt9s3HhyYP9peZXWBKn0u0nH6zSw8vJl311RvcKhvbQahfcp2VYpFUwjJkkAUNLvCv9JHlDD0SBaS0rdHOJiKoOSUpS9YcHqXa7RCPWUbghWzjUUbj4JIIgCCZTza0657/LwClhc1J0HG94vKILKJZvKR3WdmHUkQ2EXTm1ONn4bLzub2n7imBYADR/cBBvMFRyOGorTG8vDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
